name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # <--- Seu usuário Docker Hub (Secret)
          password: ${{ secrets.DOCKERHUB_TOKEN }}     # <--- Sua senha/token Docker Hub (Secret)
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: your-dockerhub-username/your-image-name:latest  # <--- Troque aqui pelo seu repositório Docker
      
      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          projectKey: your-sonarqube-project-key  # <--- Troque pelo seu projeto no SonarQube
          organization: your-sonarqube-org        # <--- Troque pela sua organização no SonarQube
          token: ${{ secrets.SONAR_TOKEN }}      # <--- Token do SonarQube (Secret)
      
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_HOST }}       # <--- IP do seu servidor (Secret)
          username: ${{ secrets.SERVER_USER }}   # <--- Usuário SSH do servidor (Secret)
          key: ${{ secrets.SERVER_SSH_KEY }}     # <--- Chave privada SSH (Secret)
          script: |
            cd /caminho/para/seu/projeto/no/servidor  # <--- Troque para a pasta do projeto no servidor
            docker-compose pull
            docker-compose up -d --build
