name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build Docker image
        run: |
          docker build -t henriqueflorentino/deploy-hq-atiprat .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        run: |
          docker push henriqueflorentino/deploy-hq-atiprat

      - name: Run deployment and analysis on remote server
        run: |
          ssh -o StrictHostKeyChecking=no aluno@201.23.3.86 << 'EOF'
            docker pull sonarqube:latest

            docker run -d --name sonarqube-temp -p 9000:9000 sonarqube:latest

            echo '⏳ Aguardando SonarQube subir...'
            sleep 60

            echo '⚙️ Rodando análise com sonar-scanner...'
            sonar-scanner \
              -Dsonar.projectKey=flask-app \
              -Dsonar.sources=. \
              -Dsonar.host.url=http://localhost:9000 \
              -Dsonar.login=admin \
              -Dsonar.password=admin || {
                echo "❌ Análise SonarQube falhou."
                docker stop sonarqube-temp
                docker rm sonarqube-temp
                exit 1
              }

            echo '✅ Análise aprovada.'
            docker stop sonarqube-temp
            docker rm sonarqube-temp

            echo '🚀 Iniciando deploy...'
            docker rm -f meu-app || true
            docker run -d --name meu-app -p 8134:5000 henriqueflorentino/deploy-hq-atiprat

            echo '✅ Deploy finalizado com sucesso.'
          EOF
