name: CI/CD Deploy - Teste

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t henriqueflorentino/deploy-hq-atiprat .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        run: |
          docker push henriqueflorentino/deploy-hq-atiprat

      - name: Run deployment and analysis on remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 201.23.3.86
          username: aluno
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 30s
          command_timeout: 10m
          script: |
            echo '🔄 Limpando containers antigos...'
            docker rm -f sonarhenriquef || true
            docker rm -f scannerhenriquef || true

            echo '🔗 Criando rede Docker personalizada (se não existir)...'
            docker network inspect sonar-net-henriquef >/dev/null 2>&1 || docker network create sonar-net-henriquef

            echo '📦 Baixando imagem do SonarQube...'
            docker pull sonarqube:latest

            echo '🚀 Subindo container do SonarQube...'
            docker run -d --name sonarhenriquef --network sonar-net-henriquef -p 8134:9000 sonarqube:latest

            echo '⏳ Aguardando SonarQube ficar pronto...'
            for i in {1..20}; do
              if curl -s http://localhost:9000/api/system/health | grep -q '"status":"UP"'; then
                echo "✅ SonarQube está pronto."
                break
              fi
              echo "⌛ Ainda não está pronto... aguardando 10s"
              sleep 10
            done

            echo '⚙️ Rodando análise com sonar-scanner via Docker...'
            docker run --rm \
              --name scannerhenriquef \
              --network sonar-net-henriquef \
              -v "$(pwd)":/usr/src \
              -w /usr/src \
              sonarsource/sonar-scanner-cli \
              sonar-scanner \
              -Dsonar.projectKey=flask-app \
              -Dsonar.sources=. \
              -Dsonar.host.url=http://sonarhenriquef:9000 \
              -Dsonar.login=admin \
              -Dsonar.password=admin || {
                echo "❌ Análise SonarQube falhou."
                docker stop sonarhenriquef
                docker rm sonarhenriquef
                exit 1
              }

            echo '✅ Análise SonarQube aprovada.'
            docker stop sonarhenriquef
            docker rm sonarhenriquef

            echo '🧹 Limpando aplicação antiga (se houver)...'
            docker rm -f meu-app || true

            echo '🚀 Subindo nova versão da aplicação...'
            docker run -d --name meu-app -p 8134:5000 henriqueflorentino/deploy-hq-atiprat

            echo '✅ Deploy finalizado com sucesso. Aplicação disponível em http://201.23.3.86:8134'
            docker ps
